// Code generated by taoctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"bookstore/api/internal/svc"

	"github.com/sllt/tao/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/add",
				Handler: AddHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/check",
				Handler: CheckHandler(serverCtx),
			},
		},
	)
}
